const API = window.OIL_PIPELINE_API || 'http://127.0.0.1:8000/api';
let current;
const $ = (id) => document.getElementById(id);
async function request(path, options) { const response = await fetch(API + path, options); if (!response.ok) throw new Error(await response.text()); return response.json(); }
async function refreshEvents() { const events = await request('/investigations'); $('events').innerHTML = events.map(event => `<button class="event ${event.status.includes('ready') ? 'complete' : ''}" data-id="${event.event_id}"><span class="dot"></span>${escapeHtml(event.name)}<small>${event.mode} · ${event.status}</small></button>`).join(''); document.querySelectorAll('.event').forEach(button => button.onclick = () => selectEvent(button.dataset.id)); }
async function selectEvent(id) { current = id; const event = await request(`/investigations/${id}`); render(event); document.querySelectorAll('.event').forEach(button => button.classList.toggle('active', button.dataset.id === id)); }
async function importStage(stage) { const input = document.querySelector(`#${stage}-path`); const path = input.value.trim(); if (!path) return; await request(`/investigations/${current}/run/${stage}`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({mode:'replay', existing_output_dir:path})}); await new Promise(resolve => setTimeout(resolve, 250)); await selectEvent(current); }
async function loadStageSummary(stage) { try { return (await request(`/investigations/${current}/stage${stage.slice(-1)}`)).summary; } catch { return {kind:'empty', message:'Summary unavailable'}; } }
function summaryMarkup(stage, summary) { if (summary.kind === 'backtracking') return `<div class="summary-grid"><div><b>Observation</b><span>${escapeHtml(summary.observation.t_obs_utc || 'n/a')}</span></div><div><b>Simulation</b><span>${escapeHtml(summary.simulation_window.start || 'n/a')} → ${escapeHtml(summary.simulation_window.end || 'n/a')}</span></div><div><b>Hypotheses</b><span>${summary.hypothesis_count}</span></div></div><h4>Top source-probability cells</h4><div class="table-wrap"><table><thead><tr><th>Time</th><th>Lon</th><th>Lat</th><th>Probability</th></tr></thead><tbody>${summary.top_cells.map(cell => `<tr><td>${escapeHtml(cell.time_utc || '')}</td><td>${Number(cell.lon_center).toFixed(3)}</td><td>${Number(cell.lat_center).toFixed(3)}</td><td>${(Number(cell.probability) * 100).toFixed(2)}%</td></tr>`).join('')}</tbody></table></div>${summary.limitations?.length ? `<div class="warning"><b>Limitations</b><ul>${summary.limitations.map(item => `<li>${escapeHtml(item)}</li>`).join('')}</ul></div>` : ''}`;
if (summary.kind === 'vessel_ranking') return `<div class="warning">${escapeHtml(summary.disclaimer)}</div><div class="table-wrap"><table><thead><tr><th>Rank</th><th>Vessel</th><th>MMSI</th><th>IMO</th><th>Score</th></tr></thead><tbody>${summary.candidates.map(candidate => `<tr><td>${candidate.rank ?? ''}</td><td>${escapeHtml(candidate.name || candidate.vessel_name || '')}</td><td>${escapeHtml(candidate.mmsi || '')}</td><td>${escapeHtml(candidate.imo || '')}</td><td>${candidate.score ?? candidate.total_score ?? ''}</td></tr>`).join('')}</tbody></table></div>`;
if (summary.kind === 'detection') return `<div class="summary-grid"><div><b>Catalog</b><span>${escapeHtml(summary.metadata.catalog_id || 'n/a')}</span></div><div><b>Acquisition</b><span>${escapeHtml(summary.metadata.acquisition_start || 'n/a')}</span></div><div><b>Detected regions</b><span>${summary.region_count}</span></div></div>`;
return `<p class="muted">${escapeHtml(summary.message || 'No summary available.')}</p>`; }
async function renderSummaries() { for (const stage of ['stage1','stage2','stage3']) { const summary = await loadStageSummary(stage); const target = document.querySelector(`#${stage}-summary`); if (target) target.innerHTML = summaryMarkup(stage, summary); } }
function render(event) { const artifacts = event.manifest.artifacts || []; const byStage = stage => artifacts.filter(a => a.stage === stage); $('workspace').innerHTML = `<div class="toolbar"><div><span class="eyebrow">INVESTIGATION</span><h2>${escapeHtml(event.name)}</h2><p>${event.event_id}</p></div><span class="badge">${event.mode}</span></div><div class="stages">${['stage1','stage2','stage3'].map((stage,i) => `<div class="stage ${byStage(stage).length ? 'ready' : ''}"><strong>${['Detection','Backtracking','Vessel ranking'][i]}</strong><small>${byStage(stage).length} artifacts · ${byStage(stage).length ? 'available' : 'waiting'}</small></div>`).join('')}</div>${['stage1','stage2','stage3'].map((stage,i) => `<section class="panel stage-panel"><div class="panel-heading"><div><h3>${['Stage 1 · Detection','Stage 2 · Backtracking','Stage 3 · Vessel ranking'][i]}</h3><p class="muted">Paste a local folder path, then import its existing outputs for offline viewing.</p></div><button class="quiet" onclick="importStage('${stage}')">Import folder</button></div><input id="${stage}-path" class="path-input" placeholder="C:\\path\\to\\${stage} outputs"><div id="${stage}-summary"><p class="muted">Loading summary...</p></div></section>`).join('')}<div class="panel"><h3>Artifacts and downloads</h3>${artifacts.length ? artifacts.map(a => `<div class="artifact"><div><strong>${escapeHtml(a.label)}</strong><span>${escapeHtml(a.relative_path)}</span></div><a href="${API}/investigations/${event.event_id}/artifacts/${a.artifact_id}" target="_blank">Open</a></div>`).join('') : '<p>No discovered artifacts yet.</p>'}</div><div class="panel"><h3>Progress</h3><div class="logs">${(event.progress || []).map(p => `${p.created_at_utc}  ${p.stage}  ${p.status}  ${p.message}`).join('\n') || 'No jobs recorded.'}</div></div>`; renderSummaries(); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); }
$('new-event').onclick = () => $('create-dialog').showModal();
$('create-form').onsubmit = async (event) => { event.preventDefault(); const form = new FormData(event.target); const created = await request('/investigations', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({name:form.get('name'), mode:form.get('mode')})}); $('create-dialog').close(); await refreshEvents(); await selectEvent(created.event_id); };
refreshEvents().catch(error => { $('workspace').innerHTML = `<div class="empty"><h2>Backend unavailable</h2><p>${escapeHtml(error.message)}</p><p>Start it with <code>uvicorn app.main:app --reload</code>.</p></div>`; });